<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net9.0-windows;net10.0-browser</TargetFrameworks>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
        <PackageReference Include="Avalonia.ThemeManager" Version="11.2.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Xaml.Behaviors.Interactions" Version="12.0.0" />

        <PackageReference Include="Material.Avalonia" Version="3.16.1" />
    </ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)' != 'net9.0-windows' ">
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AvaloniaUI.Ribbon\AvaloniaUI.Ribbon.csproj" />
		<ProjectReference Include="..\AvaloniaUI.Ribbon.Desktop\AvaloniaUI.Ribbon.Desktop.csproj" />

	</ItemGroup>
</Project>
