<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <RootNamespace>AvaloniaUI.Ribbon</RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Version>2026.2.10</Version>
        <Authors>Splitwirez, Alban Mazerolles, Rubal Walia, Sachith Liyanagama, tobitege</Authors>
        <PackageId>AvaloniaControls.Ribbon.Flowery</PackageId>
        <PackageProjectUrl>https://github.com/tobitege/Avalonia.Ribbon</PackageProjectUrl>
        <Description>Office-Like ribbon control for Avalonia framework, for cross-platform projects such as WASM and Desktop.</Description>
        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/tobitege/Avalonia.Ribbon.git</RepositoryUrl>
        <AssemblyName>AvaloniaUI.Ribbon</AssemblyName>
        <LangVersion>latest</LangVersion>
        <PackageTags>ribbon;avalonia;avaloniaui;avalonia ui;ribbon;ribbonui;ribbon ui;crossplat;crossplatform;cross platform;xplat;xplatform;wasm</PackageTags>
        <Title>Cross-Platform Ribbon control for Avalonia</Title>
        <Copyright>Partial Copyright (c) 2023 Sachith Liyanagama; Partial Copyright (c) 2026 tobitege</Copyright>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <!--owners? requireLicenseAcceptance? releaseNotes? copyright?-->
    </PropertyGroup>
    <ItemGroup>
        <Compile Update="**\*.axaml.cs">
            <DependentUpon>%(Filename)</DependentUpon>
        </Compile>
        <AvaloniaResource Include="**\*.axaml">
            <SubType>Designer</SubType>
        </AvaloniaResource>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
    <ItemGroup>
      <AvaloniaXaml Remove="Styles\Fluent\Controls\RibbonDropDownItemsPresenter.axaml" />
    </ItemGroup>
    <ItemGroup>
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        <None Include="..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.0" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.0" />
        <PackageReference Include="System.Text.Json" Version="8.0.5" />
        <PackageReference Include="Xaml.Behaviors.Interactions" Version="11.3.0.7" />
    </ItemGroup>
</Project>
